version: '3.8'

services:
  mcp-server:
    image: bhuang-mcp-server-sse:local-dev
    container_name: bhuang-mcp-server-sse
    ports:
      - "8088:9090"
    environment:
      - TZ=Asia/Shanghai
      - JAVA_OPTS=-Xms512m -Xmx1024m
    volumes:
      - ./logs:/app/logs
    networks:
      - mcp-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9090/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "3"
    labels:
      - "app=bhuang-mcp-server"
      - "env=production"
      - "version=latest"

networks:
  mcp-network:
    driver: bridge

volumes:
  mcp-logs:
    driver: local
  app-logs:
    driver: local